version: "2.3"
services:
  jupyter:
    build: .
    runtime: nvidia
    ports:
      - "80:8888"
    volumes:
      - type: bind
        source: /srv/jupyter
        target: /srv/jupyter
volumes:
  jupyter:
